### ISSUE TITLE
Need to support entity proxies

### ISSUE THREAD

**Issue by mish15** [sajari/fastentity#1]
Currently we can map entities to other entities (e.g. proxies). They can also have extended information. Not sure if we should make that part of this pkg? @dhowden thoughts?

Example:
"Bay Area" proxies to:

```
{
    "Bay Area": {
        "name": "San Francisco, CA, USA",
        "lat": 37.7833,
        "lng": 122.4167
    }
}
```

**Comment by dhowden** [comment]
I think that this is very useful, and could apply to *any* chunk of data or string in the system?  In which case I think it should be in a separate layer.

**Comment by dhowden** [comment]
Not sure how it would fit in here, especially as the output returned from `FindAll` is quite "flat" at the moment.  Feels like it is an extra layer on top, and so should probably be somewhere else.

**Comment by mish15** [comment]
yep agreed.

On Mon, Sep 21, 2015 at 10:45 PM, David Howden notifications@github.com
wrote:

> Not sure how it would fit in here, especially as the output returned from
> FindAll is quite "flat" at the moment. Feels like it is an extra layer on
> top, and so should probably be somewhere else.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sajari/fastentity/issues/1#issuecomment-141963247.

## 

_Hamish Ogilvy_
Sajari Pty Ltd
_t:  +61 (_0) 414 658 353  |  _e: *hogilvy@sajari.com
*w:_  www.sajari.com
